package myapp;
/**
 * Represents a section of a class at Virginia Tech
 * @author bgregos
 *
 */
public class Section {
	public String crn;
	public String course;
	public String title;
	public String type; //lecture, lab, etc. B = LAB, L = LECTURE
	public String hours;
	public String capacity;
	public String instructor;
	public String days;
	public String begin;
	public String end;
	public String location;
	public String exam;
	public boolean extratimes;
	public String exDays;
	public String exBegin;
	public String exEnd;
	public String exLocation;
	public String description="";
	public String available="";
	public String conflicts="";

	public Section(){

	}

	public Section(String crn, String course, String title, String type, String hours, String capacity, String instructor, String days, String begin, String end, String location, String exam)
	{
		this.crn=crn;
		this.course=course;
		this.title=title;
		this.type=type;
		this.hours=hours;
		this.capacity=capacity;
		this.instructor=instructor;
		this.days=days;
		this.begin=begin;
		this.end=end;
		this.location=location;
		this.exam=exam;
	}

	public String toString(){
		String normal = crn+" : "+course+" : "+title+" : "+type+" : "+hours+" : "+capacity+" : "+instructor+" : "+days+" : "+begin+" : "+end+" : "+location+" : "+exam;
		String extra = "";
		if(extratimes==true){
			extra = "\nAdditional Time: "+exDays+" : "+exBegin+" : "+exEnd+" : "+exLocation;
		}
		return normal+extra+"\n"+description;
	}

	//Getters and Setters, autogenerated

	public String getCrn() {
		return crn;
	}

	public void setCrn(String crn) {
		this.crn = crn;
	}

	public String getCourse() {
		return course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getHours() {
		return hours;
	}

	public void setHours(String hours) {
		this.hours = hours;
	}

	public String getCapacity() {
		return capacity;
	}

	public void setCapacity(String capacity) {
		this.capacity = capacity;
	}

	public String getInstructor() {
		return instructor;
	}

	public void setInstructor(String instructor) {
		this.instructor = instructor;
	}

	public String getDays() {
		return days;
	}

	public void setDays(String days) {
		this.days = days;
	}

	public String getBegin() {
		return begin;
	}

	public void setBegin(String begin) {
		this.begin = begin;
	}

	public String getEnd() {
		return end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getExam() {
		return exam;
	}

	public void setExam(String exam) {
		this.exam = exam;
	}

	public boolean isExtratimes() {
		return extratimes;
	}

	public void setExtratimes(boolean extratimes) {
		this.extratimes = extratimes;
	}

	public String getExDays() {
		return exDays;
	}

	public void setExDays(String exDays) {
		this.exDays = exDays;
	}

	public String getExBegin() {
		return exBegin;
	}

	public void setExBegin(String exBegin) {
		this.exBegin = exBegin;
	}

	public String getExEnd() {
		return exEnd;
	}

	public void setExEnd(String exEnd) {
		this.exEnd = exEnd;
	}

	public String getExLocation() {
		return exLocation;
	}

	public void setExLocation(String exLocation) {
		this.exLocation = exLocation;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAvailable() {
		return available;
	}

	public void setAvailable(String available) {
		this.available = available;
	}

	public String getConflicts() {
		return conflicts;
	}

	public void setConflicts(String conflicts) {
		this.conflicts = conflicts;
	}



}